### ISSUE TITLE
Database Dump file

### ISSUE THREAD

**Issue by Gomezkay** [Shashwat121/PHMS_Project#1]
Iam a student studying Computer Science, please help me with this System's Database Dump file. i'll really appreciate

**Comment by Shashwat121** [comment]
Yes, I will put the Database file this weekend. Thanks for your patience!

**Comment by Gomezkay** [comment]
okay thank you

**Comment by Shashwat121** [comment]
Hi, The database file has been added into the repo. You may have a look at it.
Thanks!
